#!/bin/bash
#
# LoreGuard IP Detection Script
# Detects the host machine's IP address for network access
#

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "Detecting host IP address for LoreGuard..."

# Function to detect IP address
detect_ip() {
    # Try multiple methods to detect IP
    
    # Method 1: Get primary network interface IP (most reliable on Linux)
    if command -v ip &> /dev/null; then
        IP=$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'src \K\S+' | head -1)
        if [ ! -z "$IP" ] && [ "$IP" != "127.0.0.1" ]; then
            echo "$IP"
            return 0
        fi
    fi
    
    # Method 2: Get IP from default route interface
    if command -v hostname &> /dev/null && command -v hostname -I &> /dev/null; then
        IP=$(hostname -I | awk '{print $1}')
        if [ ! -z "$IP" ] && [ "$IP" != "127.0.0.1" ]; then
            echo "$IP"
            return 0
        fi
    fi
    
    # Method 3: Use netstat/ss to find connected interface
    if command -v ss &> /dev/null; then
        IP=$(ss -tun | grep ':53 ' | grep -v '127.0.0.1' | head -1 | awk '{print $5}' | cut -d: -f1 | head -1)
        if [ ! -z "$IP" ] && [ "$IP" != "127.0.0.1" ]; then
            echo "$IP"
            return 0
        fi
    fi
    
    # Method 4: Check common network interfaces
    for interface in eth0 enp0s3 enp0s8 eth1 wlan0; do
        if [ -f "/sys/class/net/$interface/operstate" ]; then
            if [ "$(cat /sys/class/net/$interface/operstate)" = "up" ]; then
                IP=$(ip addr show $interface 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d/ -f1 | head -1)
                if [ ! -z "$IP" ] && [ "$IP" != "127.0.0.1" ]; then
                    echo "$IP"
                    return 0
                fi
            fi
        fi
    done
    
    # Method 5: Fallback - use ifconfig if available
    if command -v ifconfig &> /dev/null; then
        IP=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -1)
        if [ ! -z "$IP" ]; then
            echo "$IP"
            return 0
        fi
    fi
    
    # Last resort: check Docker bridge network
    if command -v docker &> /dev/null; then
        IP=$(docker network inspect bridge 2>/dev/null | grep Gateway | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -1)
        if [ ! -z "$IP" ] && [ "$IP" != "172.17.0.1" ]; then
            echo "$IP"
            return 0
        fi
    fi
    
    # If all else fails, use a warning but continue
    echo "127.0.0.1"
    return 1
}

# Detect IP
DETECTED_IP=$(detect_ip)

if [ "$DETECTED_IP" = "127.0.0.1" ]; then
    echo -e "${YELLOW}Warning: Could not detect network IP, using 127.0.0.1 (localhost only)${NC}"
    echo -e "${YELLOW}If you need network access, manually set LOREGUARD_HOST_IP environment variable${NC}"
else
    echo -e "${GREEN}Detected IP address: $DETECTED_IP${NC}"
fi

# Write to .env.detected file (for backend services)
ENV_FILE=".env.detected"
mkdir -p "$(dirname .env.detected)"

cat > "$ENV_FILE" <<EOF
# Auto-detected host IP address
# Generated by scripts/detect-ip.sh
LOREGUARD_HOST_IP=$DETECTED_IP

# Service URLs using detected IP
LOREGUARD_API_URL=http://$DETECTED_IP:8000
LOREGUARD_NORMALIZE_URL=http://$DETECTED_IP:8001
LOREGUARD_FRONTEND_URL=http://$DETECTED_IP:6060
LOREGUARD_MINIO_URL=http://$DETECTED_IP:9000
LOREGUARD_MINIO_CONSOLE_URL=http://$DETECTED_IP:9001
LOREGUARD_POSTGRES_HOST=$DETECTED_IP
LOREGUARD_REDIS_HOST=$DETECTED_IP
EOF

echo "Backend IP configuration written to $ENV_FILE"

# Write to apps/web/.env.local (for Vite - VITE_ prefix required)
FRONTEND_ENV_FILE="apps/web/.env.local"
mkdir -p "$(dirname $FRONTEND_ENV_FILE)"

cat > "$FRONTEND_ENV_FILE" <<EOF
# LoreGuard Frontend Environment Variables
# Auto-generated by scripts/detect-ip.sh
# This file is git-ignored and safe for local development

# API Configuration - MUST use VITE_ prefix for Vite to read them
VITE_API_URL=http://$DETECTED_IP:8000
VITE_API_PORT=8000
VITE_HOST_IP=$DETECTED_IP

# Development Mode
VITE_ENVIRONMENT=development
EOF

echo "Frontend IP configuration written to $FRONTEND_ENV_FILE"
echo ""
echo "Configuration files created:"
echo "  Backend:  $ENV_FILE"
echo "  Frontend: $FRONTEND_ENV_FILE"
echo ""
echo "You can source the backend file in your shell:"
echo "  source $ENV_FILE"

# Export for current session
export LOREGUARD_HOST_IP="$DETECTED_IP"
export LOREGUARD_API_URL="http://$DETECTED_IP:8000"
export LOREGUARD_NORMALIZE_URL="http://$DETECTED_IP:8001"
export LOREGUARD_FRONTEND_URL="http://$DETECTED_IP:6060"
export VITE_API_URL="http://$DETECTED_IP:8000"
export VITE_HOST_IP="$DETECTED_IP"

echo ""
echo "Environment variables exported for current session:"
echo "  LOREGUARD_HOST_IP=$DETECTED_IP"
echo "  VITE_API_URL=http://$DETECTED_IP:8000"

